// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/shahin-bayat/go-ssh-client/views/components"
)

func Admin() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><h1 class=\"text-2xl font-semibold text-gray-900 mb-4\">Dashboard</h1><p>Welcome to the admin dashboard</p><p>Please don't forget to change your password.</p></div><div class=\"h-full\"><form hx-post=\"/change-password\" hx-ext=\"response-targets\" hx-target-error=\"#change-password-error\" hx-target=\"#change-password-success\" hx-on::after-request=\"this.reset()\" class=\"h-full\"><div class=\"flex flex-col gap-2 max-w-sm\"><input type=\"text\" name=\"username\" placeholder=\"Username\" class=\"bg-gray-100 p-2 my-3 border-2 rounded\"> <input type=\"password\" name=\"current-password\" placeholder=\"Current Password\" class=\"bg-gray-100 p-2 my-3 border-2 rounded\"> <input type=\"password\" name=\"password\" placeholder=\"New Password\" class=\"bg-gray-100 p-2 my-3 border-2 rounded\"> <input type=\"password\" name=\"confirm-password\" placeholder=\"Confirm Password\" class=\"bg-gray-100 p-2 my-3 border-2 rounded\"> <button type=\"submit\" class=\"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded my-3\">Change Password</button><div id=\"change-password-error\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Error("").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div id=\"change-password-success\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Success("").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
