// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Login() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><script src=\"https://unpkg.com/htmx.org@1.9.12\"></script><script src=\"https://unpkg.com/htmx.org@1.9.12/dist/ext/response-targets.js\"></script><link rel=\"stylesheet\" href=\"/static/output.css\"><title>Login</title></head><body class=\"h-screen bg-blue-900 grid place-items-center\"><form hx-ext=\"response-targets\" hx-post=\"/login\" hx-target-error=\"#error\" class=\"text-white w-1/4 h-1/3\" id=\"login-form\"><div class=\"my-2 flex flex-col gap-y-2\"><label for=\"username\">Username:</label> <input type=\"text\" name=\"username\" id=\"username\" class=\"p-1.5 rounded-sm text-black\"></div><div class=\"my-2 flex flex-col gap-y-2\"><label for=\"password\">Password:</label> <input type=\"password\" name=\"password\" id=\"password\" class=\"p-1.5 rounded-sm text-black\"></div><div class=\"flex flex-col justify-center mt-6\"><button type=\"submit\" class=\"rounded-sm border-2 border-white p-1.5 hover:bg-blue-400\">Login</button></div><div id=\"error\"></div></form></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
